### ISSUE TITLE
Error starting server 

### ISSUE THREAD

**Issue by SoilihBenSoilih** [ocamllabs/vscode-ocaml-platform#543]
I got this issue after installing it from the VSCode Marketplace.
It's shows this in the notifications : 

```
Error starting server : sandbox initialition failed:
Command failed with see output channel for more details
Source : Ocaml Plateform( Extension)
```

But the output channel is empty !!!

Anybody knows how to solve that?

**Comment by mnxn** [comment]
That's very strange. Is there anything in the `OCaml Language Server` output channel either?

If not, are there any errors in the developer console? (_Help → Toggle Developer Tools_)

**Comment by SoilihBenSoilih** [comment]
Hello, 

I don't know how to go to the output channel on the `Ocaml Language server`.
but in the developer console, there're many.
Here is what it shows : 

``` 
console.ts:137 [Extension Host] Error: write EPIPE	at afterWriteDispatched (internal/stream_base_commons.js:154:25)	at writeGeneric (internal/stream_base_commons.js:145:3)	at Socket._writeGeneric (net.js:786:11)	at Socket._write (net.js:798:8)	at doWrite (_stream_writable.js:403:12)	at writeOrBuffer (_stream_writable.js:387:5)	at Socket.Writable.write (_stream_writable.js:318:11)	at Interface._writeToOutput (readline.js:337:17)	at Interface.prompt (readline.js:303:10)	at Interface.question (readline.js:316:12)	at /home/soilih/.vscode/extensions/hackwaly.ocaml-0.6.44/out/src/merlin.js:59:26	at new Promise (<anonymous>)	at /home/soilih/.vscode/extensions/hackwaly.ocaml-0.6.44/out/src/merlin.js:55:20	at processTicksAndRejections (internal/process/task_queues.js:97:5)
v @ console.ts:137
log.ts:296   ERR spawn ocamlmerlin ENOENT: Error: spawn ocamlmerlin ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
	at onErrorNT (internal/child_process.js:469:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:21)
console.ts:137 [Extension Host] Error: Unexpected SIGPIPE	at process.<anonymous> (/usr/share/code/resources/app/out/bootstrap.js:1:370)	at process.emit (events.js:315:20)
v @ console.ts:137
[Extension Host] rejected promise not handled within 1 second: Error: write EPIPE
v @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: write EPIPE	at afterWriteDispatched (internal/stream_base_commons.js:154:25)	at writeGeneric (internal/stream_base_commons.js:145:3)	at Socket._writeGeneric (net.js:786:11)	at Socket._write (net.js:798:8)	at doWrite (_stream_writable.js:403:12)	at writeOrBuffer (_stream_writable.js:387:5)	at Socket.Writable.write (_stream_writable.js:318:11)	at Interface._writeToOutput (readline.js:337:17)	at Interface.prompt (readline.js:303:10)	at Interface.question (readline.js:316:12)	at /home/soilih/.vscode/extensions/hackwaly.ocaml-0.6.44/out/src/merlin.js:59:26	at new Promise (<anonymous>)	at /home/soilih/.vscode/extensions/hackwaly.ocaml-0.6.44/out/src/merlin.js:55:20	at processTicksAndRejections (internal/process/task_queues.js:97:5)
v @ console.ts:137
mainThreadExtensionService.ts:59 [[object Object]]write EPIPE
$onExtensionRuntimeError @ mainThreadExtensionService.ts:59
mainThreadExtensionService.ts:60 Error: write EPIPE
	at afterWriteDispatched (internal/stream_base_commons.js:154)
	at writeGeneric (internal/stream_base_commons.js:145)
	at Socket._writeGeneric (net.js:786)
	at Socket._write (net.js:798)
	at doWrite (_stream_writable.js:403)
	at writeOrBuffer (_stream_writable.js:387)
	at Socket.Writable.write (_stream_writable.js:318)
	at Interface._writeToOutput (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/readline.js:337)
	at Interface.prompt (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/readline.js:303)
	at Interface.question (/usr/share/code/resources/app/out/vs/code/electron-browser/workbench/readline.js:316)
	at /home/soilih/.vscode/extensions/hackwaly.ocaml-0.6.44/out/src/merlin.js:59
	at new Promise (<anonymous>)
	at /home/soilih/.vscode/extensions/hackwaly.ocaml-0.6.44/out/src/merlin.js:55
	at processTicksAndRejections (internal/process/task_queues.js:97)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60
console.ts:137 [Extension Host] Error: write EPIPE	at afterWriteDispatched (internal/stream_base_commons.js:154:25)	at writeGeneric (internal/stream_base_commons.js:145:3)	at Socket._writeGeneric (net.js:786:11)	at Socket._write (net.js:798:8)	at doWrite (_stream_writable.js:403:12)	at writeOrBuffer (_stream_writable.js:387:5)	at Socket.Writable.write (_stream_writable.js:318:11)	at Interface._writeToOutput (readline.js:337:17)	at Interface.prompt (readline.js:303:10)	at Interface.question (readline.js:316:12)	at /home/soilih/.vscode/extensions/hackwaly.ocaml-0.6.44/out/src/merlin.js:59:26	at new Promise (<anonymous>)	at /home/soilih/.vscode/extensions/hackwaly.ocaml-0.6.44/out/src/merlin.js:55:20	at processTicksAndRejections (internal/process/task_queues.js:97:5)
v @ console.ts:137
console.ts:137 [Extension Host] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed	at doWrite (_stream_writable.js:399:19)	at writeOrBuffer (_stream_writable.js:387:5)	at Socket.Writable.write (_stream_writable.js:318:11)	at Interface._writeToOutput (readline.js:337:17)	at Interface.prompt (readline.js:303:10)	at Interface.question (readline.js:311:12)	at /home/soilih/.vscode/extensions/hackwaly.ocaml-0.6.44/out/src/merlin.js:59:26	at new Promise (<anonymous>)	at /home/soilih/.vscode/extensions/hackwaly.ocaml-0.6.44/out/src/merlin.js:55:20	at processTicksAndRejections (internal/process/task_queues.js:97:5)
v @ console.ts:137
log.ts:296 
```

It's still continue, but it's something related to merlin i think. 
I have merlin installed, the version is : `4.1-411`

**Comment by mnxn** [comment]
> at /home/soilih/.vscode/extensions/hackwaly.ocaml-0.6.44/out/src/merlin.js:55

You have another OCaml extension installed (`hackwaly.ocaml`). Uninstall it, and make sure the only OCaml extension you have is OCaml Platform (`ocamllabs.ocaml-platform`).

**Comment by SoilihBenSoilih** [comment]
I have done what you said but the error is still the same...
The errors in developer console are not there no more, but 
i still have this notification : 
```
Error starting server : sandbox initialition failed:
Command failed with see output channel for more details
Source : Ocaml Plateform( Extension)
``` 
And still nothing in the output channel.

**Comment by mnxn** [comment]
To be clear, you are looking in the `OCaml Platform Extension` output channel? 

It looks like this:
![image](https://user-images.githubusercontent.com/25037249/110171081-0108c480-7db0-11eb-82da-573adb1a457b.png)

**Comment by SoilihBenSoilih** [comment]
No, the extension didn't work with vs code after installed it, the errors were not highlighted and things like that.
But it was my bad, I had pined an executable named `ocaml-lsp-server` and when i had installed the ocaml-lsp 
with the command  `opam install ocaml-lsp-server`, i had an error. But after i had removed the pin, then re-install, 
all works fine now. It was my bad, sorry !
And thank you very much !

**Comment by mnxn** [comment]
Awesome! Glad you got it working.
