### ISSUE TITLE
vscode code visually reports errors even when there isn’t one

### ISSUE THREAD

**Issue by lubegasimon** [ocamllabs/vscode-ocaml-platform#553]
vscode visually reports errors in a project even when the projects builds perfectly. This brings about poor user experience since one is unable to;
- freely navigate modules
- take a glimpse of a type when hovering over a function for example

It also causes visual studio code to use significant energy of the machine.

I’m using the same Opam switch for sandbox.

- `vscode platform `v1.8.0``
- `Ocaml-lsp-server `v1.4.0``
- `dune `v2.8.2``

Machine specs
```
macOS Catalina
v10.15.7 (19H15)
```

<img width="1122" alt="Screenshot 2021-03-08 at 08 49 06" src="https://user-images.githubusercontent.com/34124177/110366463-5e726f00-8057-11eb-950e-ef66ce908974.png">
<img width="455" alt="Screenshot 2021-03-08 at 09 42 01" src="https://user-images.githubusercontent.com/34124177/110366483-66caaa00-8057-11eb-9338-95d9a78101b1.png">

**Comment by mnxn** [comment]
Can you post the logs in the `OCaml Platform Extension` and `OCaml Language Server` output channel please?

**Comment by lubegasimon** [comment]
```
[2021-03-09 08:18:37.956] [exthost] [info] extension host started
[2021-03-09 08:18:37.985] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2021-03-09 08:18:37.985] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-03-09 08:18:37.992] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-03-09 08:18:37.993] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/debug-auto-launch/dist/extension
[2021-03-09 08:18:37.995] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-03-09 08:18:37.995] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main
[2021-03-09 08:18:38.005] [exthost] [info] ExtensionService#_doActivateExtension GitHub.vscode-pull-request-github {"startup":true,"extensionId":{"value":"GitHub.vscode-pull-request-github","_lower":"github.vscode-pull-request-github"},"activationEvent":"*"}
[2021-03-09 08:18:38.005] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/simon/.vscode/extensions/github.vscode-pull-request-github-0.24.0/dist/extension
[2021-03-09 08:18:38.020] [exthost] [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker {"startup":true,"extensionId":{"value":"streetsidesoftware.code-spell-checker","_lower":"streetsidesoftware.code-spell-checker"},"activationEvent":"*"}
[2021-03-09 08:18:38.020] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/simon/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/dist/extension.js
[2021-03-09 08:18:38.031] [exthost] [info] ExtensionService#_doActivateExtension wayou.vscode-todo-highlight {"startup":true,"extensionId":{"value":"wayou.vscode-todo-highlight","_lower":"wayou.vscode-todo-highlight"},"activationEvent":"*"}
[2021-03-09 08:18:38.031] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/simon/.vscode/extensions/wayou.vscode-todo-highlight-1.0.4/src/extension
[2021-03-09 08:18:38.072] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2021-03-09 08:18:38.072] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js
[2021-03-09 08:18:38.083] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-03-09 08:18:38.083] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2021-03-09 08:18:38.193] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-03-09 08:18:38.193] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github/dist/extension.js
[2021-03-09 08:18:38.198] [exthost] [info] eager extensions activated
[2021-03-09 08:18:38.206] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-03-09 08:18:38.206] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/emmet/dist/node/emmetNodeMain
[2021-03-09 08:18:38.210] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-03-09 08:18:38.210] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2021-03-09 08:18:38.212] [exthost] [info] ExtensionService#_doActivateExtension vscode.testing-editor-contributions {"startup":false,"extensionId":{"value":"vscode.testing-editor-contributions","_lower":"vscode.testing-editor-contributions"},"activationEvent":"onStartupFinished"}
[2021-03-09 08:18:38.212] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/testing-editor-contributions/dist/extension.js
[2021-03-09 08:18:38.216] [exthost] [info] ExtensionService#_doActivateExtension CodeStream.codestream {"startup":false,"extensionId":{"value":"CodeStream.codestream","_lower":"codestream.codestream"},"activationEvent":"onStartupFinished"}
[2021-03-09 08:18:38.217] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/simon/.vscode/extensions/codestream.codestream-10.6.1/dist/extension
[2021-03-09 08:18:38.227] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens {"startup":false,"extensionId":{"value":"eamodio.gitlens","_lower":"eamodio.gitlens"},"activationEvent":"onStartupFinished"}
[2021-03-09 08:18:38.227] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/simon/.vscode/extensions/eamodio.gitlens-11.3.0/dist/gitlens
[2021-03-09 08:18:38.251] [exthost] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":false,"extensionId":{"value":"esbenp.prettier-vscode","_lower":"esbenp.prettier-vscode"},"activationEvent":"onStartupFinished"}
[2021-03-09 08:18:38.251] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/simon/.vscode/extensions/esbenp.prettier-vscode-5.9.2/dist/extension
[2021-03-09 08:18:38.284] [exthost] [info] ExtensionService#_doActivateExtension waderyan.gitblame {"startup":false,"extensionId":{"value":"waderyan.gitblame","_lower":"waderyan.gitblame"},"activationEvent":"onStartupFinished"}
[2021-03-09 08:18:38.284] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/simon/.vscode/extensions/waderyan.gitblame-6.0.2/dist/index
[2021-03-09 08:18:40.964] [exthost] [info] extension host terminating: received terminate message from renderer
[2021-03-09 08:18:41.978] [exthost] [info] exiting with code 0
[2021-03-09 08:18:42.826] [exthost] [info] extension host started
[2021-03-09 08:18:42.867] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2021-03-09 08:18:42.868] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-03-09 08:18:42.875] [exthost] [info] ExtensionService#_doActivateExtension badochov.ocaml-formatter {"startup":false,"extensionId":{"value":"badochov.ocaml-formatter","_lower":"badochov.ocaml-formatter"},"activationEvent":"onLanguage:ocaml"}
[2021-03-09 08:18:42.875] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/simon/.vscode/extensions/badochov.ocaml-formatter-1.14.0/out/extension.js
[2021-03-09 08:18:42.877] [exthost] [info] ExtensionService#_doActivateExtension ocamllabs.ocaml-platform {"startup":false,"extensionId":{"value":"ocamllabs.ocaml-platform","_lower":"ocamllabs.ocaml-platform"},"activationEvent":"onLanguage:ocaml"}
[2021-03-09 08:18:42.877] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/simon/.vscode/extensions/ocamllabs.ocaml-platform-1.8.0/dist/vscode_ocaml_platform.js
[2021-03-09 08:18:43.021] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-03-09 08:18:43.021] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/debug-auto-launch/dist/extension
[2021-03-09 08:18:43.024] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-03-09 08:18:43.024] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main
[2021-03-09 08:18:43.041] [exthost] [info] ExtensionService#_doActivateExtension GitHub.vscode-pull-request-github {"startup":true,"extensionId":{"value":"GitHub.vscode-pull-request-github","_lower":"github.vscode-pull-request-github"},"activationEvent":"*"}
[2021-03-09 08:18:43.041] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/simon/.vscode/extensions/github.vscode-pull-request-github-0.24.0/dist/extension
[2021-03-09 08:18:43.060] [exthost] [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker {"startup":true,"extensionId":{"value":"streetsidesoftware.code-spell-checker","_lower":"streetsidesoftware.code-spell-checker"},"activationEvent":"*"}
[2021-03-09 08:18:43.060] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/simon/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/dist/extension.js
[2021-03-09 08:18:43.078] [exthost] [info] ExtensionService#_doActivateExtension wayou.vscode-todo-highlight {"startup":true,"extensionId":{"value":"wayou.vscode-todo-highlight","_lower":"wayou.vscode-todo-highlight"},"activationEvent":"*"}
[2021-03-09 08:18:43.078] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/simon/.vscode/extensions/wayou.vscode-todo-highlight-1.0.4/src/extension
[2021-03-09 08:18:43.196] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2021-03-09 08:18:43.196] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js
[2021-03-09 08:18:43.272] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-03-09 08:18:43.272] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2021-03-09 08:18:43.377] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-03-09 08:18:43.377] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github/dist/extension.js
[2021-03-09 08:18:43.450] [exthost] [info] eager extensions activated
[2021-03-09 08:18:43.478] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-03-09 08:18:43.478] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/emmet/dist/node/emmetNodeMain
[2021-03-09 08:18:43.482] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-03-09 08:18:43.482] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2021-03-09 08:18:43.485] [exthost] [info] ExtensionService#_doActivateExtension vscode.testing-editor-contributions {"startup":false,"extensionId":{"value":"vscode.testing-editor-contributions","_lower":"vscode.testing-editor-contributions"},"activationEvent":"onStartupFinished"}
[2021-03-09 08:18:43.485] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/testing-editor-contributions/dist/extension.js
[2021-03-09 08:18:43.486] [exthost] [info] ExtensionService#_doActivateExtension CodeStream.codestream {"startup":false,"extensionId":{"value":"CodeStream.codestream","_lower":"codestream.codestream"},"activationEvent":"onStartupFinished"}
[2021-03-09 08:18:43.486] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/simon/.vscode/extensions/codestream.codestream-10.6.1/dist/extension
[2021-03-09 08:18:43.503] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens {"startup":false,"extensionId":{"value":"eamodio.gitlens","_lower":"eamodio.gitlens"},"activationEvent":"onStartupFinished"}
[2021-03-09 08:18:43.503] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/simon/.vscode/extensions/eamodio.gitlens-11.3.0/dist/gitlens
[2021-03-09 08:18:43.537] [exthost] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":false,"extensionId":{"value":"esbenp.prettier-vscode","_lower":"esbenp.prettier-vscode"},"activationEvent":"onStartupFinished"}
[2021-03-09 08:18:43.537] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/simon/.vscode/extensions/esbenp.prettier-vscode-5.9.2/dist/extension
[2021-03-09 08:18:43.578] [exthost] [info] ExtensionService#_doActivateExtension waderyan.gitblame {"startup":false,"extensionId":{"value":"waderyan.gitblame","_lower":"waderyan.gitblame"},"activationEvent":"onStartupFinished"}
[2021-03-09 08:18:43.578] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/simon/.vscode/extensions/waderyan.gitblame-6.0.2/dist/index
[2021-03-09 08:19:07.140] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"extensionId":{"value":"vscode.configuration-editing","_lower":"vscode.configuration-editing"},"activationEvent":"onLanguage:jsonc"}
[2021-03-09 08:19:07.140] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/configuration-editing/dist/configurationEditingMain
[2021-03-09 08:19:07.147] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"extensionId":{"value":"vscode.json-language-features","_lower":"vscode.json-language-features"},"activationEvent":"onLanguage:jsonc"}
[2021-03-09 08:19:07.147] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/client/dist/node/jsonClientMain
[2021-03-09 08:19:07.160] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"extensionId":{"value":"vscode.typescript-language-features","_lower":"vscode.typescript-language-features"},"activationEvent":"onLanguage:jsonc"}
[2021-03-09 08:19:07.160] [exthost] [info] ExtensionService#loadCommonJSModule file:///Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension
```

**Comment by lubegasimon** [comment]
Could you guide me on how to do these because I don’t seem to find something relevant?

**Comment by mnxn** [comment]
If you click on the dropdown in the output tab, you should be able to select the `OCaml Platform Extension` and `OCaml Language Server` output channels:

![image](https://user-images.githubusercontent.com/25037249/110423918-c8d6df80-8056-11eb-80d7-35ebc0735b03.png)

![image](https://user-images.githubusercontent.com/25037249/110424070-0c314e00-8057-11eb-960f-ce1f6a43a621.png)

**Comment by lubegasimon** [comment]
OCaml Platform Extension logs -> https://gist.github.com/lubegasimon/f2bbd189cc1a6bb7aec46773d742cb06

OCaml Language server : 
```
[Trace - 8:45:37 AM] Sending request 'initialize - (0)'.
[Trace - 8:45:37 AM] Received response 'initialize - (0)' in 320ms.
[Trace - 8:45:37 AM] Sending notification 'initialized'.
[Trace - 8:45:37 AM] Sending notification 'textDocument/didOpen'.
[Trace - 8:45:37 AM] Sending request 'textDocument/documentSymbol - (1)'.
[Trace - 8:45:37 AM] Sending request 'textDocument/codeAction - (2)'.
[Trace - 8:45:37 AM] Received response 'textDocument/documentSymbol - (1)' in 14ms.
[Trace - 8:45:37 AM] Received response 'textDocument/codeAction - (2)' in 14ms.
[Trace - 8:45:37 AM] Sending request 'textDocument/foldingRange - (3)'.
[Trace - 8:45:37 AM] Received response 'textDocument/foldingRange - (3)' in 1ms.
[Trace - 8:45:37 AM] Sending request 'textDocument/codeLens - (4)'.
[Trace - 8:45:37 AM] Received response 'textDocument/codeLens - (4)' in 1ms.
[Trace - 8:45:37 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 8:45:38 AM] Sending request 'textDocument/codeAction - (5)'.
[Trace - 8:45:38 AM] Received response 'textDocument/codeAction - (5)' in 3ms.
[Trace - 8:45:38 AM] Sending request 'textDocument/documentSymbol - (6)'.
[Trace - 8:45:38 AM] Received response 'textDocument/documentSymbol - (6)' in 1ms.
[Trace - 8:45:43 AM] Sending request 'textDocument/codeAction - (7)'.
[Trace - 8:45:43 AM] Received response 'textDocument/codeAction - (7)' in 4ms.
[Trace - 8:45:48 AM] Sending request 'textDocument/hover - (8)'.
[Trace - 8:45:48 AM] Received response 'textDocument/hover - (8)' in 2ms.
[Trace - 8:45:49 AM] Sending request 'textDocument/codeLens - (9)'.
[Trace - 8:45:49 AM] Received response 'textDocument/codeLens - (9)' in 1ms.
[Trace - 8:45:50 AM] Sending request 'shutdown - (10)'.
[Trace - 8:45:50 AM] Received response 'shutdown - (10)' in 1ms.
[Trace - 8:45:50 AM] Sending notification 'exit'.
[Trace - 8:45:50 AM] Sending request 'initialize - (0)'.
[Trace - 8:45:51 AM] Received response 'initialize - (0)' in 317ms.
[Trace - 8:45:51 AM] Sending notification 'initialized'.
[Trace - 8:45:51 AM] Sending notification 'textDocument/didOpen'.
[Trace - 8:45:51 AM] Sending request 'textDocument/documentSymbol - (1)'.
[Trace - 8:45:51 AM] Sending request 'textDocument/codeAction - (2)'.
[Trace - 8:45:51 AM] Received response 'textDocument/documentSymbol - (1)' in 13ms.
[Trace - 8:45:51 AM] Received response 'textDocument/codeAction - (2)' in 14ms.
[Trace - 8:45:51 AM] Sending request 'textDocument/foldingRange - (3)'.
[Trace - 8:45:51 AM] Received response 'textDocument/foldingRange - (3)' in 1ms.
[Trace - 8:45:51 AM] Sending request 'textDocument/codeLens - (4)'.
[Trace - 8:45:51 AM] Received response 'textDocument/codeLens - (4)' in 2ms.
[Trace - 8:45:51 AM] Received notification 'textDocument/publishDiagnostics'.
[Trace - 8:45:51 AM] Sending request 'textDocument/codeAction - (5)'.
[Trace - 8:45:51 AM] Received response 'textDocument/codeAction - (5)' in 2ms.
```

**Comment by mnxn** [comment]
Hmm, I can't see anything that indicates the cause of the crash.

Can you set the `ocaml.trace.server` setting to `verbose` and show the logs after a crash please?

You can change it by going to the VSCode preferences UI and searching for `ocaml.trace.server`.

**Comment by lubegasimon** [comment]
The crash actually happens sometimes, not always! But the visual error warnings seems not linger

**Comment by lubegasimon** [comment]
Regardless;
- OCaml-language server -> https://gist.github.com/lubegasimon/0c5a86cf86b6e8782e9c32afda3be0b6
- OCaml platform ext -> https://gist.github.com/lubegasimon/f4f3f27faa603b4e4ced905625a60302

**Comment by mnxn** [comment]
Thank you for the logs. My thinking was that seeing an error message for the crash would help determine the cause for visual errors too, but I still don't see anything out of the ordinary.

@rgrinberg, @tmattio: any ideas?

**Comment by peter-jerry-ye** [comment]
> Also this has been running for hours now
> 
> <img alt="Screenshot 2021-03-09 at 10 51 11" width="249" src="https://user-images.githubusercontent.com/34124177/110436611-800a3f80-80c5-11eb-96c7-5a2f45884db4.png">

Maybe check `Ocaml Commands`?

**Comment by peter-jerry-ye** [comment]
> > > Also this has been running for hours now
> > > <img alt="Screenshot 2021-03-09 at 10 51 11" width="249" src="https://user-images.githubusercontent.com/34124177/110436611-800a3f80-80c5-11eb-96c7-5a2f45884db4.png">
> > 
> > 
> > Maybe check `Ocaml Commands`?
> 
> Could you please clarify on what you mean because all I see when I click on that is
> <img alt="Screenshot 2021-03-09 at 12 17 30" width="466" src="https://user-images.githubusercontent.com/34124177/110447744-93230c80-80d1-11eb-93bb-2515b1e78ead.png">
> ?

Check the output channel named `Ocaml Commands`.

**Comment by lubegasimon** [comment]
> Check the output channel named `Ocaml Commands`.

I see
```
$ /usr/local/bin/opam var root
$ /usr/local/bin/opam var root
/Users/simon/.opam
/Users/simon/.opam


$ /usr/local/bin/opam switch list -s --root /Users/simon/.opam
/Users/simon/alcotest
/Users/simon/dune
/Users/simon/odocmkgen
4.02.0
4.06.1
4.11.2
4.12.0
default

$ /usr/local/bin/opam exec --switch=default --root /Users/simon/.opam -- ocamlc --version
4.10.0

$ /usr/local/bin/opam exec --switch=vscode-ocaml-toolchain.4.10.0 --root /Users/simon/.vscode-ocaml/opam -- true

$ /usr/local/bin/opam exec --switch=default --root /Users/simon/.opam -- which ocamlformat
$ /usr/local/bin/opam exec --switch=default --root /Users/simon/.opam -- which ocamllsp
/Users/simon/.opam/default/bin/ocamllsp

/Users/simon/.opam/default/bin/ocamlformat

$ /usr/local/bin/opam exec --switch=default --root /Users/simon/.opam -- ocamllsp --version
$ /usr/local/bin/opam exec --switch=default --root /Users/simon/.opam -- ocamlformat --version
1.4.0

0.15.0

$ /usr/local/bin/opam exec --switch=default --root /Users/simon/.opam -- which ocamllsp
/Users/simon/.opam/default/bin/ocamllsp

$ /usr/local/bin/opam update --switch=vscode-ocaml-toolchain.4.10.0 --root /Users/simon/.vscode-ocaml/opam
Another process has locked /Users/simon/.vscode-ocaml/opam/config.lock, waiting (C-c to abort)... 
```

**Comment by rgrinberg** [comment]
> $ /usr/local/bin/opam update --switch=vscode-ocaml-toolchain.4.10.0 --root /Users/simon/.vscode-ocaml/opam
Another process has locked /Users/simon/.vscode-ocaml/opam/config.lock, waiting (C-c to abort)... 

Are we running opam concurrently in some cases @tmattio

**Comment by kkirstein** [comment]
Very recently I am also observing regular crashes of the lsp-server ("Crashed 5 times in the last 3 minutes...", see above). Lately, I switched from `ocaml 4.11.1` to `ocaml 4.12.0` and have these versions:
`ocaml-lsp-server pinned to github.com/ocaml/ocaml-lsp.git`
`ocaml-platform 1.8.2`

Could be related to the issue above. Here is some log output, maybe this info helps:
```
[Error - 15:58:05] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\kayuwe.kirstein\.vscode\extensions\ocamllabs.ocaml-platform-1.8.2\node_modules\vscode-jsonrpc\lib\common\connection.js:1044:27)
    at Object.dispose (c:\Users\kayuwe.kirstein\.vscode\extensions\ocamllabs.ocaml-platform-1.8.2\node_modules\vscode-languageclient\lib\common\client.js:73:35)
    at LanguageClient.handleConnectionClosed (c:\Users\kayuwe.kirstein\.vscode\extensions\ocamllabs.ocaml-platform-1.8.2\node_modules\vscode-languageclient\lib\common\client.js:2424:42)
    at LanguageClient.handleConnectionClosed (c:\Users\kayuwe.kirstein\.vscode\extensions\ocamllabs.ocaml-platform-1.8.2\node_modules\vscode-languageclient\lib\node\main.js:155:15)
    at closeHandler (c:\Users\kayuwe.kirstein\.vscode\extensions\ocamllabs.ocaml-platform-1.8.2\node_modules\vscode-languageclient\lib\common\client.js:2411:18)
    at CallbackList.invoke (c:\Users\kayuwe.kirstein\.vscode\extensions\ocamllabs.ocaml-platform-1.8.2\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
    at Emitter.fire (c:\Users\kayuwe.kirstein\.vscode\extensions\ocamllabs.ocaml-platform-1.8.2\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
    at closeHandler (c:\Users\kayuwe.kirstein\.vscode\extensions\ocamllabs.ocaml-platform-1.8.2\node_modules\vscode-jsonrpc\lib\common\connection.js:256:26)
    at CallbackList.invoke (c:\Users\kayuwe.kirstein\.vscode\extensions\ocamllabs.ocaml-platform-1.8.2\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
    at Emitter.fire (c:\Users\kayuwe.kirstein\.vscode\extensions\ocamllabs.ocaml-platform-1.8.2\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
    at StreamMessageReader.fireClose (c:\Users\kayuwe.kirstein\.vscode\extensions\ocamllabs.ocaml-platform-1.8.2\node_modules\vscode-jsonrpc\lib\common\messageReader.js:40:27)
    at Socket.<anonymous> (c:\Users\kayuwe.kirstein\.vscode\extensions\ocamllabs.ocaml-platform-1.8.2\node_modules\vscode-jsonrpc\lib\common\messageReader.js:125:42)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:674:12)
ocamllsp: internal error, uncaught exception:
          Fiber_unix__Scheduler.Abort(_)
          Raised at Fiber_unix__Scheduler.run in file "fiber-unix/src/scheduler.ml", line 390, characters 15-30
          Called from Dune__exe__Ocaml_lsp_server.start in file "ocaml-lsp-server/src/ocaml_lsp_server.ml", line 892, characters 2-299
          Called from Lsp__Logger.with_sections in file "lsp/src/logger.ml", line 155, characters 8-12
          Re-raised at Lsp__Logger.with_sections in file "lsp/src/logger.ml", line 161, characters 4-19
          Called from Lsp__Logger.with_log_file in file "lsp/src/logger.ml", line 187, characters 10-34
          Re-raised at Lsp__Logger.with_log_file in file "lsp/src/logger.ml", line 193, characters 6-21
          Called from Cmdliner_term.app.(fun) in file "ocaml-lsp-server/vendor/cmdliner/src/cmdliner_term.ml", line 25, characters 19-24
          Called from Cmdliner.Term.run in file "ocaml-lsp-server/vendor/cmdliner/src/cmdliner.ml", line 117, characters 32-39
```

**Comment by kkirstein** [comment]
The above reported crash seems to be an issue of `ocaml-lsp-server`, so I filed an issue there: https://github.com/ocaml/ocaml-lsp/issues/395

**Comment by rgrinberg** [comment]
Indeed, this is an issue with LSP
